### ISSUE TITLE
Morning Survey Columns Missing

### ISSUE THREAD

**Issue by nickdotreid** [kpwhri/heartsteps#178]
Some participant's exported data is missing columns for questions. This happened because the columns are dynamically generated and are based on the survey responses from the participants, not the questions asked to a participant.

**Comment by samurphy11** [comment]
Hi Nick
Are the same set of questions asked each day?  Or does the set of questions
asked differ by day?
Best
Susan

**Comment by klasnja** [comment]
Susan, the same questions are being asked every day. The problem is that if
a participant never answered a question, the way the export was originally
coded is that that column would never show up in his/her file. Nick is
fixing this. We will have all columns for everyone, with clearly indicated
missing responses.

**Comment by samurphy11** [comment]
Thanks to you and Nick!
Susan

**Comment by nickdotreid** [comment]
The questions are the same everyday, but the order is randomized.

Essentially, this ticket is about me pulling data from the wrong table to
populate the exported file.
